using System.Collections;
using System.Collections.Generic;
using Unity.AI.Navigation;
using UnityEngine;

//Script used to visualze the noisemap generated by the MapGenerator and Noise scripts

public class MapDisplay : MonoBehaviour {

    public static MapDisplay instance;
    
    public Renderer textureRender;
    public MeshFilter meshFilter;
    public MeshRenderer meshRenderer;
    public NavMeshSurface meshSurface;

    public void DrawTexture (Texture2D text) { //Displays a 2d Texture

        instance = this;
        
        textureRender.sharedMaterial.mainTexture = text;
        textureRender.transform.localScale = new Vector3 (text.width, 1, text.height);
    }

    public void DrawMesh (MeshData meshData, Texture2D texture) { //Displays a mesh from meshdata and a texture

        instance = this;
        
        meshFilter.sharedMesh = meshData.CreateMesh ();
        meshFilter.gameObject.GetComponent<MeshCollider> ().sharedMesh = meshFilter.sharedMesh;
        meshRenderer.sharedMaterial.mainTexture = texture;
        
    }

    public void DrawNavMesh () {
        meshSurface.BuildNavMesh ();
        GenerationStepManager.instance.MeshGenerated(); //fires off void to tell system mesh has been generated
    }
    
}
